### PR TITLE
Ensure bindir exists before running certain commands

### PR DESCRIPTION
**Pull request by SgtCoDFish**
This prevents confusion on an initial checkout

### CODE REVIEW

**Comment by inteon** [comment]
@SgtCoDFish see https://github.com/cert-manager/csi-driver-spiffe/pull/47

**Comment by SgtCoDFish** [comment]
> @SgtCoDFish see https://github.com/cert-manager/csi-driver-spiffe/pull/47

Ouch, I hope nobody else got hit by that! I'll review that when it's passing

**Comment by inteon** [comment]
> > @SgtCoDFish see #47
> 
> Ouch, I hope nobody else got hit by that! I'll review that when it's passing

No, it's just the way that the CertificateRequest for this e2e test is generated which is wrong.

**Pull request merged**
